volumes:
  rose-volume:

services:
  rose-database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - rose-volume:/etc/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: rose-dev
      MONGO_INITDB_ROOT_PASSWORD: rose-dev

  rose-database-dashboard:
    image: mongo-express
    restart: always
    depends_on:
      - rose-database
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rose-dev
      ME_CONFIG_MONGODB_ADMINPASSWORD: rose-dev
      ME_CONFIG_MONGODB_URL: mongodb://rose-dev:rose-dev@rose-database:27017/